### ISSUE TITLE
your code is horrible pls lint it!

### ISSUE THREAD

**Issue by rhoit** [nepal-js/nepaljs.org#6]
intro to eslint and how to configure it!

**Comment by jonathanclarke** [comment]
Hi @rhoit - do you want to do this talk for the next meetup?

**Comment by rhoit** [comment]
@jonathanclarke lets do it!

**Comment by jonathanclarke** [comment]
awesome.  How long will your talk take? 5/10/30 mins?

I'm going to need the following:

- Full name
- Employer
- Avatar
- Where people can find you (linkedin / twitter, etc)
Let me know if you want to practice the talk as well for some constructive feedback.

**Comment by rhoit** [comment]
I haven't planned yet about the time will get back after a while.
- Full name : Rohit Man Amatya
- Avatar : https://rhoit.com/img/svg/profile.svg
- telegram: [@rhoit ](https://t.me/rhoit)
- twitter: [@rhoitman](https://twitter.com/messages/compose?recipient_id=740249803&text=Hello)

**Comment by jonathanclarke** [comment]
Awesome. I'll add you as a speaker for the event.

**Comment by rhoit** [comment]
which day on November?

**Comment by jonathanclarke** [comment]
https://www.meetup.com/javascript-developers-nepal-meetup-group/events/289640811/
November 30; 6pm.  @rhoit

**Comment by rhoit** [comment]
https://rhoit.com/talks/2022-nepaljs/
